---
- name: make ftb_servers dirs
  file:
    state: directory
    path: ~/ftb_servers/{{item}}
  with_items:
    - zips
    - "{{ server_name }}"
- name: get FTBInfinity server
  get_url:
    url: "{{ server_url }}"
    dest: ~/ftb_servers/zips/{{ server_name }}-{{ server_version }}.zip
- name: unpack server
  unarchive:
    src: ~/ftb_servers/zips/{{ server_name }}-{{ server_version }}.zip
    dest: ~/ftb_servers/{{ server_name }}
    copy: no
    creates: ~/ftb_servers/{{ server_name }}/ServerStart.sh
- name: make ServerStart executable
  file:
    path: ~/ftb_servers/{{ server_name }}/ServerStart.sh
    mode: 0755
- name: install dtach
  portage:
    name: dtach
    state: present
