---
- name: make ftb_servers dirs
  file:
    state: directory
    path: ~/ftb_servers/{{item}}
  with_items:
    - zips
    - FTBInfinityServer
- name: get FTBInfinity server
  get_url:
    url: http://ftb.cursecdn.com/FTB2/modpacks/FTBInfinity/1_1_0/FTBInfinityServer.zip
    dest: ~/ftb_servers/zips/FTBInfinityServer-1.1.0.zip
- name: unpack server
  unarchive:
    src: ~/ftb_servers/zips/FTBInfinityServer-1.1.0.zip
    dest: ~/ftb_servers/FTBInfinityServer
    copy: no
    creates: ~/ftb_servers/FTBInfinityServer/ServerStart.sh
- name: remove disabled mods from pack
  file:
    state: absent
    path: ~/ftb_servers/FTBInfinityServer/mods/{{item}}
  with_items:
    - witchery-1.7.10-0.22.0.jar
    - BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar
    - NotEnoughResources-1.7.10-0.1.0.86.jar
    - JourneyMapServer1.0.2_MC1.7.10.jar
- name: configure server
  template:
    src: server.properties.j2
    dest: ~/ftb_servers/FTBInfinityServer/server.properties
- name: accept EULA
  lineinfile:
    dest: ~/ftb_servers/FTBInfinityServer/eula.txt
    state: present
    regexp: "^eula="
    line: "eula=TRUE"
- name: start server
  #command: screen -S FTBInfinityServer ServerStart.sh -d ~/ftb_servers/FTBInfinityServer
  command: dtach -n ~/ftb_servers/FTBInfinityServer.sock ./ServerStart.sh
  args:
    chdir: ~/ftb_servers/FTBInfinityServer
